version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: quejas_db
    environment:
      MYSQL_DATABASE: quejas
      MYSQL_USER: abd
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: